version: "2"
services:
  web:
    build: .
    environment:
      NODE_ENV: development
      PORT: 3000
    ports:
      - '3000:3000'
    volumes:
      - '.:/home/admin/app'
      - /home/admin/app/node_modules
    command: node_modules/.bin/nodemon --exec npm start
